=== TPeter12/A24E5ZWebXML/A24E5Z_XMLTask/A24E5ZDOMParse/A24E5Z_XSD.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- Gyökérelem -->
  <xs:element name="A24E5Z_nyilvantartas">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Tulajdonos" type="TulajdonosType" minOccurs="1" maxOccurs="unbounded"/>
        <xs:element name="Gepjarmu" type="GepjarmuType" minOccurs="1" maxOccurs="unbounded"/>
        <xs:element name="Alkatresz" type="AlkatreszType" minOccurs="1" maxOccurs="unbounded"/>
        <xs:element name="Tartalmaz" type="TartalmazType" minOccurs="1" maxOccurs="unbounded"/>
        <xs:element name="Uzemanyag" type="UzemanyagType" minOccurs="1" maxOccurs="unbounded"/>
        <xs:element name="Tankolas" type="TankolasType" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>

        <!-- Kulcsok-->

        <xs:key name="Tulajdonos_kulcs">
            <xs:selector xpath="Tulajdonos"/>
            <xs:field xpath="@okod"/>
        </xs:key>

        <xs:key name="Gepjarmu_kulcs">
            <xs:selector xpath="Gepjarmu"/>
            <xs:field xpath="@gkod"/>
        </xs:key>

        <xs:key name="Alkatresz_kulcs">
            <xs:selector xpath="Alkatresz"/>
            <xs:field xpath="@akod"/>
        </xs:key>

        <xs:key name="Uzemanyag_kulcs">
            <xs:selector xpath="Uzemanyag"/>
            <xs:field xpath="@ukod"/>
        </xs:key>
        
        <xs:key name="Tartalmaz_kulcs">
            <xs:selector xpath="Tartalmaz"/>
            <xs:field xpath="@xkod"/>
        </xs:key>

        <!-- Idegen kulcsok-->

        <xs:keyref name="Tulajdonos_FK" refer="Gepjarmu_kulcs">
            <xs:selector xpath="Tulajdonos"/>
            <xs:field xpath="@O_G"/>
        </xs:keyref>

        <xs:keyref name="Alkatresz_FK" refer="Tartalmaz_kulcs">
            <xs:selector xpath="Alkatresz"/>
            <xs:field xpath="@A_X"/>
        </xs:keyref>

        <xs:keyref name="Uzemanyag_FK" refer="Gepjarmu_kulcs">
            <xs:selector xpath="Uzemanyag"/>
            <xs:field xpath="@U_G"/>
        </xs:keyref>

        <xs:keyref name="Tankolas_FK" refer="Gepjarmu_kulcs">
            <xs:selector xpath="Tankolas"/>
            <xs:field xpath="@T_G"/>
        </xs:keyref>

        <xs:keyref name="Tartalmaz_FK" refer="Gepjarmu_kulcs">
            <xs:selector xpath="Tartalmaz"/>
            <xs:field xpath="@X_G"/>
        </xs:keyref>

        <!-- Unique kulcsok-->

    <xs:unique name="Tankolas_kulcs">
            <xs:selector xpath="Tankolas"/>
            <xs:field xpath="@tkod"/>
        </xs:unique>
    </xs:element>

  <!-- Tulajdonos -->
    <xs:complexType name="TulajdonosType">
      <xs:sequence>
        <xs:element name="Nev" type="xs:string"/>
        <xs:element name="Telefonszam" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
        <xs:element name="Cim" type="CimType"/>
      </xs:sequence>
      <xs:attribute name="okod" type="xs:ID" use="required"/>
    </xs:complexType>

    <xs:complexType name="CimType">
        <xs:sequence>
            <xs:element name="Varos" type="xs:string"></xs:element>
            <xs:element name="Utca" type="xs:string"></xs:element>
            <xs:element name="Hazszam" type="xs:string"></xs:element>
        </xs:sequence>
    </xs:complexType>

  <!-- Gépkocsik -->
          <xs:complexType name="GepjarmuType">
            <xs:sequence>
              <xs:element name="Tipus" type="xs:string"/>
              <xs:element name="GyartasiEv" type="xs:gYear"/>
              <xs:element name="Marka" type="xs:string"/>
              <xs:element name="Km_ora" type="xs:integer"/>
            </xs:sequence>
            <xs:attribute name="gkod" type="xs:ID" use="required"/>
            <xs:attribute name="alvazszam" type="xs:string" use="optional"/>
            <xs:attribute name="rendszam" type="xs:string" use="required"/>
            <xs:attribute name="O_G" type="xs:IDREF" use="required"/>
          </xs:complexType>

  <!-- Alkatrészek -->
          <xs:complexType name="AlkatreszType">
            <xs:sequence>
              <xs:element name="Nev" type="xs:string"/>
              <xs:element name="Tipus" type="xs:string"/>
              <xs:element name="Cikkszam" type="xs:string"/>
              <xs:element name="Darab" type="xs:integer"/>
              <xs:element name="Gyarto" type="xs:string"/>
              <xs:element name="Szarmazas" type="xs:string"/>
              <xs:element name="Szolgaltatas" type="xs:string"/>
            </xs:sequence>
            <xs:attribute name="akod" type="xs:ID" use="required"/>
            <xs:attribute name="A_X" type="xs:IDREF" use="required"/>
          </xs:complexType>

    <!-- Tartalmaz -->
    <xs:complexType name="TartalmazType">
      <xs:sequence>
        <xs:element name="Ar" type="xs:integer"/>
        <xs:element name="Jegyzokonyv" type="xs:string"/>
      </xs:sequence>
      <xs:attribute name="xkod" type="xs:ID" use="required"/>
      <xs:attribute name="X_G" type="xs:IDREF" use="required"/>
    </xs:complexType>


  <!-- Üzemanyag -->
          <xs:complexType name="UzemanyagType">
            <xs:sequence>
              <xs:element name="Tipus" type="xs:string"/>
        <xs:element name="Ar" type="xs:integer"/>
        <xs:element name="Gyarto" type="xs:string"/>
      </xs:sequence>
      <xs:attribute name="ukod" type="xs:ID" use="required"/>
      <xs:attribute name="U_G" type="xs:IDREF" use="required"/>
    </xs:complexType>

  <!-- Tankolás -->
    <xs:complexType name="TankolasType">
      <xs:sequence>
        <xs:element name="Datum" type="xs:date"/>
        <xs:element name="Liter" type="xs:integer"/>
        <xs:element name="Osszeg" type="xs:integer"/>
      </xs:sequence>
      <xs:attribute name="tkod" type="xs:ID" use="required"/>
      <xs:attribute name="T_G" type="xs:IDREF" use="required"/>
    </xs:complexType>

</xs:schema>

=== TPeter12/A24E5ZWebXML/A24E5Z_XMLTask/A24E5ZDOMParse/A24E5Z_XMLA24E5Z.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<A24E5Z_nyilvantartas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="A24E5Z_XSD.xsd">
  
  <Tulajdonos okod="O001">
        
    <Nev>Kovács János</Nev>
        
    <Telefonszam>+36-30-123-4567</Telefonszam>
        
    <Telefonszam>+36-30-123-4567</Telefonszam>
        
    <Cim>
              
      <Varos>Budapest</Varos>
              
      <Utca>Fő utca</Utca>
              
      <Hazszam>12</Hazszam>
          
    </Cim>
    
  </Tulajdonos>
  
  <Gepjarmu O_G="O001" alvazszam="ALV123456789" gkod="G001" rendszam="ABC-123">
        
    <Tipus>Személyautó</Tipus>
        
    <GyartasiEv>2015</GyartasiEv>
        
    <Marka>Opel</Marka>
        
    <Km_ora>120000</Km_ora>
    
  </Gepjarmu>
  
  <Gepjarmu O_G="O001" alvazszam="ALV987654321" gkod="G002" rendszam="XYZ-987">
        
    <Tipus>Személyautó</Tipus>
        
    <GyartasiEv>2020</GyartasiEv>
        
    <Marka>Toyota</Marka>
        
    <Km_ora>75000</Km_ora>
    
  </Gepjarmu>
  
  <Gepjarmu O_G="O001" alvazszam="ALV112233445" gkod="G003" rendszam="LMN-456">
        
    <Tipus>Teherautó</Tipus>
        
    <GyartasiEv>2020</GyartasiEv>
        
    <Marka>Mercedes</Marka>
        
    <Km_ora>40000</Km_ora>
    
  </Gepjarmu>
  
  <Alkatresz A_X="X001" akod="A001">
        
    <Nev>Olajszűrő</Nev>
        
    <Tipus>Motor</Tipus>
        
    <Cikkszam>OS123</Cikkszam>
        
    <Darab>1</Darab>
        
    <Gyarto>Bosch</Gyarto>
        
    <Szarmazas>Németország</Szarmazas>
        
    <Szolgaltatas>Csere</Szolgaltatas>
    
  </Alkatresz>
  
  <Alkatresz A_X="X002" akod="A002">
        
    <Nev>Fékbetét</Nev>
        
    <Tipus>Fék</Tipus>
        
    <Cikkszam>FB456</Cikkszam>
        
    <Darab>4</Darab>
        
    <Gyarto>TRW</Gyarto>
        
    <Szarmazas>Franciaország</Szarmazas>
        
    <Szolgaltatas>Csere</Szolgaltatas>
    
  </Alkatresz>
  
  <Alkatresz A_X="X003" akod="A003">
        
    <Nev>Légszűrő</Nev>
        
    <Tipus>Motor</Tipus>
        
    <Cikkszam>LS789</Cikkszam>
        
    <Darab>1</Darab>
        
    <Gyarto>Mann</Gyarto>
        
    <Szarmazas>Németország</Szarmazas>
        
    <Szolgaltatas>Csere</Szolgaltatas>
    
  </Alkatresz>
  
  <Tartalmaz X_G="G001" xkod="X001">
        
    <Ar>6000</Ar>
        
    <Jegyzokonyv>Olajszűrő csere</Jegyzokonyv>
    
  </Tartalmaz>
  
  <Tartalmaz X_G="G002" xkod="X002">
        
    <Ar>7400</Ar>
        
    <Jegyzokonyv>Fékbetét csere</Jegyzokonyv>
    
  </Tartalmaz>
  
  <Tartalmaz X_G="G003" xkod="X003">
        
    <Ar>4000</Ar>
        
    <Jegyzokonyv>Légszűrő csere</Jegyzokonyv>
    
  </Tartalmaz>
  
  <Uzemanyag U_G="G001" ukod="U001">
        
    <Tipus>Benzin</Tipus>
        
    <Ar>600</Ar>
        
    <Gyarto>MOL</Gyarto>
    
  </Uzemanyag>
  
  <Uzemanyag U_G="G002" ukod="U002">
        
    <Tipus>Dízel</Tipus>
        
    <Ar>630</Ar>
        
    <Gyarto>MOL</Gyarto>
    
  </Uzemanyag>
  
  <Uzemanyag U_G="G003" ukod="U003">
        
    <Tipus>Benzin</Tipus>
        
    <Ar>600</Ar>
        
    <Gyarto>MOL</Gyarto>
    
  </Uzemanyag>
  
  <Tankolas T_G="G001" tkod="T001">
          
    <Datum>2025-11-20</Datum>
          
    <Liter>50</Liter>
          
    <Osszeg>29000</Osszeg>
    
  </Tankolas>
  
  <Tankolas T_G="G002" tkod="T002">
          
    <Datum>2025-11-22</Datum>
          
    <Liter>40</Liter>
          
    <Osszeg>23200</Osszeg>
    
  </Tankolas>
  
</A24E5Z_nyilvantartas>

=== TPeter12/A24E5ZWebXML/A24E5Z_XMLTask/A24E5ZDOMParse/A24E5Z_XML.xml
<?xml version="1.0" encoding="UTF-8"?>

<A24E5Z_nyilvantartas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="A24E5Z_XSD.xsd">

<Tulajdonos okod="O001">
    <Nev>Kovács János</Nev>
    <Telefonszam>+36-30-123-4567</Telefonszam>
    <Telefonszam>+36-30-123-4567</Telefonszam>
    <Cim>
        <Varos>Budapest</Varos>
        <Utca>Fő utca</Utca>
        <Hazszam>12</Hazszam>
    </Cim>
</Tulajdonos>


<Gepjarmu gkod="G001" alvazszam="ALV123456789" rendszam="ABC-123" O_G="O001">
    <Tipus>Személyautó</Tipus>
    <GyartasiEv>2015</GyartasiEv>
    <Marka>Opel</Marka>
    <Km_ora>120000</Km_ora>
</Gepjarmu>

<Gepjarmu gkod="G002" alvazszam="ALV987654321" rendszam="XYZ-987" O_G="O001">
    <Tipus>Személyautó</Tipus>
    <GyartasiEv>2018</GyartasiEv>
    <Marka>Ford</Marka>
    <Km_ora>60000</Km_ora>
</Gepjarmu>

<Gepjarmu gkod="G003" alvazszam="ALV112233445" rendszam="LMN-456" O_G="O001">
    <Tipus>Teherautó</Tipus>
    <GyartasiEv>2020</GyartasiEv>
    <Marka>Mercedes</Marka>
    <Km_ora>40000</Km_ora>
</Gepjarmu>


<Alkatresz akod="A001" A_X="X001">
    <Nev>Olajszűrő</Nev>
    <Tipus>Motor</Tipus>
    <Cikkszam>OS123</Cikkszam>
    <Darab>1</Darab>
    <Gyarto>Bosch</Gyarto>
    <Szarmazas>Németország</Szarmazas>
    <Szolgaltatas>Csere</Szolgaltatas>
</Alkatresz>

<Alkatresz akod="A002" A_X="X002">
    <Nev>Fékbetét</Nev>
    <Tipus>Fék</Tipus>
    <Cikkszam>FB456</Cikkszam>
    <Darab>4</Darab>
    <Gyarto>TRW</Gyarto>
    <Szarmazas>Franciaország</Szarmazas>
    <Szolgaltatas>Csere</Szolgaltatas>
</Alkatresz>

<Alkatresz akod="A003" A_X="X003">
    <Nev>Légszűrő</Nev>
    <Tipus>Motor</Tipus>
    <Cikkszam>LS789</Cikkszam>
    <Darab>1</Darab>
    <Gyarto>Mann</Gyarto>
    <Szarmazas>Németország</Szarmazas>
    <Szolgaltatas>Csere</Szolgaltatas>
</Alkatresz>

<Tartalmaz xkod="X001" X_G="G001">
    <Ar>6000</Ar>
    <Jegyzokonyv>Olajszűrő csere</Jegyzokonyv>
</Tartalmaz>

<Tartalmaz xkod="X002" X_G="G002">
    <Ar>7400</Ar>
    <Jegyzokonyv>Fékbetét csere</Jegyzokonyv>
</Tartalmaz>

<Tartalmaz xkod="X003" X_G="G003">
    <Ar>4000</Ar>
    <Jegyzokonyv>Légszűrő csere</Jegyzokonyv>
</Tartalmaz>


<Uzemanyag ukod="U001"  U_G="G001">
    <Tipus>Benzin</Tipus>
    <Ar>580</Ar>
    <Gyarto>MOL</Gyarto>
</Uzemanyag>

<Uzemanyag ukod="U002" U_G="G002">
    <Tipus>Dízel</Tipus>
    <Ar>600</Ar>
    <Gyarto>MOL</Gyarto>
</Uzemanyag>

<Uzemanyag ukod="U003"  U_G="G003">
    <Tipus>Benzin</Tipus>
    <Ar>580</Ar>
    <Gyarto>MOL</Gyarto>
</Uzemanyag>

<Tankolas tkod="T001" T_G="G001">
      <Datum>2025-11-20</Datum>
      <Liter>50</Liter>
      <Osszeg>29000</Osszeg>
</Tankolas>

<Tankolas tkod="T002" T_G="G002">
      <Datum>2025-11-22</Datum>
      <Liter>40</Liter>
      <Osszeg>23200</Osszeg>
</Tankolas>

</A24E5Z_nyilvantartas>
